os:
 - linux
 - osx
language: cpp
branches:
  only:
    - master
    - /openmw-.*$/
before_install:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./CI/before_install.linux.sh; fi
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/before_install.osx.sh; fi
before_script:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./CI/before_script.linux.sh; fi
 - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ./CI/before_script.osx.sh; fi
script:
 - cd ./build
 - make -j4
after_script:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./openmw_test_suite; fi
notifications:
  recipients:
    - lgromanowski+travis.ci@gmail.com
    - corrmage+travis-ci@gmail.com
  email:
    on_success: change
    on_failure: always
